- name: gghcode env init
  hosts: local
  gather_facts: no
  roles:
    - role: shell
      vars:
        oh_my_zsh_plugins:
          - git
          - asdf
          - docker
          - zsh-autosuggestions
          - zsh-syntax-highlighting

    - role: ide
    - role: sdk
      vars:
        git_editor: vim
        git_author_email: gyuhwan.a.kim@gmail.com
        git_author_name: Gyuhwan Kim
        asdf_plugins:
          - name: golang
          - name: python
          - name: terraform

    - role: browsers
    - role: productivity
