- name: gghcode env init
  hosts: local
  gather_facts: no
  roles:
    - role: shell

    - role: ide
    - role: sdk
      vars:
        git_editor: vim
        git_author_email: gyuhwan.a.kim@gmail.com
        git_author_name: Gyuhwan Kim

    - role: browsers